app = "samba-web"
primary_region = "ams"

[build]
  dockerfile = "apps/web/Dockerfile"

[[services]]
  internal_port = 3000
  protocol = "tcp"
  [[services.ports]]
    handlers = ["http"]
    port = 80
  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
